version: '3.8'
services:
  app:
    container_name: crudAPP
    image: jairodh/examen:v16
    restart: always
    environment:
      DB_HOST: mariadbcrud
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: examen
    ports:
      - 8089:80
    depends_on:
      - db
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: examen
    volumes:
      - vol-mariadb-crud:/var/lib/mysql
volumes:
    vol-mariadb-crud:
